apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-frontend-deployment
spec:
  replicas: 3  # En producción, queremos 3 réplicas del frontend

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-backend-deployment
spec:
  replicas: 3  # En producción, también queremos 3 réplicas del backend
