apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: default
spec:
  selector:
    app: flask-backend  # Selector para el Deployment del backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: NodePort

